### ISSUE TITLE
UIImage+Filter.m category conflicts with standard UIControls

### ISSUE THREAD

**Issue by dgoldman-ebay** [jameswomack/iOS-Image-Filters#5]
This category method:
```
@implementation NGImage (Filter)
- (CIImage *)CIImage {
  return [CIImage imageWithCGImage:self.CGImage];
}
```
Has problems with views containing either `UISegmentedControl` or `UISwitch`.

For `UISegmentedControl`, under iOS 8 there is a crash (`EXC_BAD_ACCESS` inside `[UIImage imageWithRenderingMode:]`). Under iOS 7 there is no crash, but the `UISegmentedControl` is badly rendered onscreen.

For `UISwitch`, under iOS 8 the switch is rendered badly onscreen.

I've created a [small sample project](https://github.com/dgoldman-ebay/image-filter-problem) that illustrates these issues. (It currently contains a `UISegmentedControl` in its main storyboard. You can replace that with a `UISwitch` to confirm the iOS 8 issue there.)

I'm wondering whether the `- (CIImage *)CIImage` method is still necessary under iOS 7 and/or 8. Perhaps it can be conditionally compiled, or eliminated altogether?

**Comment by jameswomack** [comment]
@dgoldman-ebay I apologize—my company email address changed and it resulted in some dropped Github notifications. 

Does this issue remain?

**Comment by dgoldman-ebay** [comment]
Thanks for catching this, @jameswomack.

I don't know of anything relevant that might have changed in the past couple of weeks, so I presume that the problem remains, as described above.

**Comment by jameswomack** [comment]
@dgoldman-ebay Still looking into the matter. This may be relevant in the interim: https://stackoverflow.com/questions/26065808/bsxpcmessage-received-error-for-message-connection-interrupted

**Comment by jameswomack** [comment]
@dgoldman-ebay I can see that Apple has now implemented some of the methods from this project. That's what's causing this issue and I'll get it fixed.

**Comment by jameswomack** [comment]
Using a category method seems to fix it. I've committed this change.

**Comment by dgoldman-ebay** [comment]
Thanks, @jameswomack, I appreciate your effort. I'll give your new code a try tomorrow.

At first glance it looks like you're using a compile-time test to determine whether to proceed as for iOS 8 or for pre-iOS 8. But since the same binary might be run on any version of iOS, don't you need a runtime test instead? (Also, see the original description above re iOS 7 rendering issues.)

**Comment by jameswomack** [comment]
@dgoldman-ebay Code updated, and now also published to CocoaPods. There's no longer a build-time check. I haven't seen any rendering issues on 7 or 8 since I namespace `CIImage` and `imageClampingToExtent`.
![Example app screener](https://www.dropbox.com/s/qwbsd77so3nyiq9/Screen%20Shot%202015-02-17%20at%201.04.54%20AM.png?raw=1)

**Comment by dgoldman-ebay** [comment]
Looks good, @jameswomack! Thanks.
